name: Scraper
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: pip install
        run: |
          pip install -r requirements.txt
      - name: scraper
        run: |
          python archive.py scrape -j 10 > commit-message.md
          cat commit-message.md
      - name: git config user
        run: |
          curl -s -u ${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }} https://api.github.com/users/${GITHUB_ACTOR} > ${GITHUB_ACTOR}.json
          git config user.email "$(cat ${GITHUB_ACTOR}.json | jq -r .email)"
          git config user.name "scrapy"
      - name: commit changes
        run: |
          git add docs/snapshots/
          git commit --file=commit-message.md --allow-empty
      - name: push changes
        run: |
          git gc --aggressive --prune=now
          git push || (git pull --no-edit --rebase && git push)
